[2021-04-07 16:00:01,007] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trata_relatorios.popula_relatorios 2021-04-07T14:00:00+00:00 [queued]>
[2021-04-07 16:00:01,044] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trata_relatorios.popula_relatorios 2021-04-07T14:00:00+00:00 [queued]>
[2021-04-07 16:00:01,045] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-07 16:00:01,045] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-07 16:00:01,046] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-07 16:00:01,079] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): popula_relatorios> on 2021-04-07T14:00:00+00:00
[2021-04-07 16:00:01,084] {standard_task_runner.py:52} INFO - Started process 34432 to run task
[2021-04-07 16:00:01,091] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trata_relatorios', 'popula_relatorios', '2021-04-07T14:00:00+00:00', '--job-id', '46', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_chamados.py', '--cfg-path', '/tmp/tmp46_l1ptv', '--error-file', '/tmp/tmpevd2dnv4']
[2021-04-07 16:00:01,095] {standard_task_runner.py:77} INFO - Job 46: Subtask popula_relatorios
[2021-04-07 16:00:01,173] {logging_mixin.py:104} INFO - Running <TaskInstance: trata_relatorios.popula_relatorios 2021-04-07T14:00:00+00:00 [running]> on host ce03b876977a
[2021-04-07 16:00:01,245] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clecio.antao@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trata_relatorios
AIRFLOW_CTX_TASK_ID=popula_relatorios
AIRFLOW_CTX_EXECUTION_DATE=2021-04-07T14:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-07T14:00:00+00:00
[2021-04-07 16:00:02,713] {logging_mixin.py:104} INFO - Token:  dGVjYmFu#6a5151f74950c15b8332c0fae1ef5a01ba56f5a7
[2021-04-07 16:00:07,313] {logging_mixin.py:104} INFO - Paginas:  5000
[2021-04-07 16:00:07,319] {logging_mixin.py:104} INFO - Contador:  1
[2021-04-07 16:00:07,319] {logging_mixin.py:104} INFO - Linhas:  0
[2021-04-07 16:00:19,180] {logging_mixin.py:104} INFO - Paginas:  5000
[2021-04-07 16:00:19,181] {logging_mixin.py:104} INFO - Contador:  2
[2021-04-07 16:00:19,181] {logging_mixin.py:104} INFO - Linhas:  5000
[2021-04-07 16:00:21,336] {python.py:118} INFO - Done. Returned value was: None
[2021-04-07 16:00:21,400] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=trata_relatorios, task_id=popula_relatorios, execution_date=20210407T140000, start_date=20210407T160001, end_date=20210407T160021
[2021-04-07 16:00:21,540] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-04-07 16:00:21,543] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 34432
[2021-04-07 16:00:21,571] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-07 16:00:21,614] {process_utils.py:66} INFO - Process psutil.Process(pid=34432, status='terminated', exitcode=1, started='16:00:00') (34432) terminated with exit code 1
